-- =============================================
-- V1: Criacao da tabela de veiculos
-- =============================================

CREATE TABLE veiculos (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca       VARCHAR2(100)  NOT NULL,
    modelo      VARCHAR2(100)  NOT NULL,
    versao      VARCHAR2(100)  NOT NULL,
    ano         NUMBER(4)      NOT NULL,
    categoria   VARCHAR2(50),
    criado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_veiculo UNIQUE (marca, modelo, versao, ano)
);

COMMENT ON TABLE  veiculos          IS 'Catalogo de veiculos para analise competitiva';
COMMENT ON COLUMN veiculos.marca    IS 'Fabricante do veiculo (ex: Ford, Toyota)';
COMMENT ON COLUMN veiculos.modelo   IS 'Modelo do veiculo (ex: Ranger, Hilux)';
COMMENT ON COLUMN veiculos.versao   IS 'Versao/trim do veiculo (ex: Raptor, SR)';
COMMENT ON COLUMN veiculos.ano      IS 'Ano de fabricacao';
COMMENT ON COLUMN veiculos.categoria IS 'Segmento do veiculo (ex: Pickup, SUV, Sedan)';