-- =============================================
-- V2: Criacao da tabela de especificacoes tecnicas
-- =============================================

CREATE TABLE especificacoes (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id  NUMBER         NOT NULL,
    atributo    VARCHAR2(100)  NOT NULL,
    valor       VARCHAR2(255),
    unidade     VARCHAR2(50),
    categoria   VARCHAR2(50),
    criado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_espec_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE,
    CONSTRAINT uq_espec UNIQUE (veiculo_id, atributo)
);

COMMENT ON TABLE  especificacoes           IS 'Especificacoes tecnicas de cada veiculo';
COMMENT ON COLUMN especificacoes.atributo  IS 'Nome do atributo (ex: Potencia, Motor, Tracao)';
COMMENT ON COLUMN especificacoes.valor     IS 'Valor do atributo (ex: 392, 3.0L V6 EcoBoost)';
COMMENT ON COLUMN especificacoes.unidade   IS 'Unidade de medida (ex: cv, Nm, mm)';
COMMENT ON COLUMN especificacoes.categoria IS 'Categoria da spec (ex: Motor, Desempenho, Dimensoes)';